"""add question_type and correct_answers

Revision ID: 8d51209cd0ae
Revises: efa6a6a6d05b
Create Date: 2026-10-02 22:29:42.870975

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d51209cd0ae'
down_revision: Union[str, None] = 'efa6a6a6d05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=20), nullable=False, server_default='multiple_choice'))
        batch_op.add_column(sa.Column('correct_answers', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###
